CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- DROP TABLE IF EXISTS vector_store;

CREATE TABLE IF NOT EXISTS vector_store
(
    embedding vector(1536) NOT NULL,
    metadata  jsonb,
    content   text,
    id        uuid default uuid_generate_v4() PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS chat_cost
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prompt_tokens     INTEGER                                 NOT NULL,
    completion_tokens INTEGER                                 NOT NULL,
    total_tokens      INTEGER                                 NOT NULL,
    cost_input        DOUBLE PRECISION                        NOT NULL,
    cost_output       DOUBLE PRECISION                        NOT NULL,
    cost_total        DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_chat_cost PRIMARY KEY (id)
);
